const FOOTBALL_COUNTRY_HINTS: Array<[RegExp, string]> = [
  [/\b(south korea|korea republic)\b|южн\w*\s+коре|коре\w*\s+республик/i, "South Korea"],
  [/\bnorth macedonia\b|северн\w*\s+македон/i, "North Macedonia"],
  [/\bbosnia(?:\s+and\s+herzegovina)?\b|босни|герцеговин/i, "Bosnia and Herzegovina"],
  [/\bnew zealand\b|нов\w*\s+зеланд/i, "New Zealand"],
  [/\bsaudi arabia\b|саудов/i, "Saudi Arabia"],
  [/\bunited arab emirates\b|\buae\b|объединенн\w*\s+арабск|\bоаэ\b/i, "United Arab Emirates"],
  [/\bcosta rica\b|коста[\s-]*рик/i, "Costa Rica"],
  [/\bel salvador\b|сальвадор/i, "El Salvador"],
  [/\bsouth africa\b|южн\w*\s+африк|\bюар\b/i, "South Africa"],
  [/\bkyrgyzstan\b|кыргыз|киргиз/i, "Kyrgyzstan"],
  [/\buzbekistan\b|узбекистан/i, "Uzbekistan"],
  [/\bazerbaijan\b|азербайджан/i, "Azerbaijan"],
  [/\bmontenegro\b|черногор/i, "Montenegro"],
  [/\bparaguay\b|парагва/i, "Paraguay"],
  [/\becuador\b|эквадор/i, "Ecuador"],
  [/\bvenezuela\b|венесуэл/i, "Venezuela"],
  [/\bguatemala\b|гватемал/i, "Guatemala"],
  [/\bnicaragua\b|никарагу/i, "Nicaragua"],
  [/\bhonduras\b|гондурас/i, "Honduras"],
  [/\bdominican\b|доминикан/i, "Dominican Republic"],
  [/\bpuerto rico\b|пуэрто[\s-]*рик/i, "Puerto Rico"],
  [/\bpanama\b|панам/i, "Panama"],
  [/\bbolivia\b|боливи/i, "Bolivia"],
  [/\bcolombia\b|колумби/i, "Colombia"],
  [/\buruguay\b|уругва/i, "Uruguay"],
  [/\bargentina\b|аргентин/i, "Argentina"],
  [/\bbrazil\b|бразили/i, "Brazil"],
  [/\bchile\b|чили/i, "Chile"],
  [/\bperu\b|перу(?:ан)?/i, "Peru"],
  [/\bmexico\b|мексик/i, "Mexico"],
  [/\bcanada\b|канад/i, "Canada"],
  [/\busa\b|\bunited states\b|сша|соединенн\w*\s+штат/i, "USA"],
  [/\bengland\b|англи/i, "England"],
  [/\bscotland\b|шотланд/i, "Scotland"],
  [/\bwales\b|уэльс/i, "Wales"],
  [/\bireland\b|ирланд/i, "Ireland"],
  [/\biceland\b|исланд/i, "Iceland"],
  [/\bfinland\b|финлянд/i, "Finland"],
  [/\bsweden\b|швеци/i, "Sweden"],
  [/\bnorway\b|норвеги/i, "Norway"],
  [/\bdenmark\b|дани/i, "Denmark"],
  [/\bnetherlands\b|нидерланд|голланд/i, "Netherlands"],
  [/\bbelgium\b|бельги/i, "Belgium"],
  [/\bfrance\b|франци/i, "France"],
  [/\bgermany\b|германи/i, "Germany"],
  [/\bspain\b|испани/i, "Spain"],
  [/\bportugal\b|португали/i, "Portugal"],
  [/\bitaly\b|итали/i, "Italy"],
  [/\bswitzerland\b|швейцари/i, "Switzerland"],
  [/\baustria\b|австри/i, "Austria"],
  [/\bczech(?:ia|\s+republic)\b|чехи/i, "Czech Republic"],
  [/\bslovakia\b|словаки/i, "Slovakia"],
  [/\bslovenia\b|словени/i, "Slovenia"],
  [/\bcroatia\b|хорвати/i, "Croatia"],
  [/\bserbia\b|серби/i, "Serbia"],
  [/\bromania\b|румыни/i, "Romania"],
  [/\bbulgaria\b|болгари/i, "Bulgaria"],
  [/\bhungary\b|венгри/i, "Hungary"],
  [/\bpoland\b|польш/i, "Poland"],
  [/\blithuania\b|литв/i, "Lithuania"],
  [/\blatvia\b|латви/i, "Latvia"],
  [/\bestonia\b|эстони/i, "Estonia"],
  [/\bmoldova\b|молдов/i, "Moldova"],
  [/\bukraine\b|украин/i, "Ukraine"],
  [/\bbelarus\b|беларус/i, "Belarus"],
  [/\brussia\b|росси/i, "Russia"],
  [/\bgeorgia\b|грузи/i, "Georgia"],
  [/\barmenia\b|армени/i, "Armenia"],
  [/\balbania\b|албани/i, "Albania"],
  [/\bkosovo\b|косов/i, "Kosovo"],
  [/\bmalta\b|мальт/i, "Malta"],
  [/\bcyprus\b|кипр/i, "Cyprus"],
  [/\bgreece\b|греци/i, "Greece"],
  [/\bturkey\b|турци/i, "Turkey"],
  [/\bisrael\b|израил/i, "Israel"],
  [/\bkazakhstan\b|казахстан/i, "Kazakhstan"],
  [/\bchina\b|кита/i, "China"],
  [/\bjapan\b|япони/i, "Japan"],
  [/\bkorea\b|коре/i, "South Korea"],
  [/\baustralia\b|австрали/i, "Australia"],
  [/\bpakistan\b|пакистан/i, "Pakistan"],
  [/\bbangladesh\b|бангладеш/i, "Bangladesh"],
  [/\bafghanistan\b|афганистан/i, "Afghanistan"],
  [/\bnepal\b|непал/i, "Nepal"],
  [/\bsri lanka\b|шри[\s-]*ланк/i, "Sri Lanka"],
  [/\bindia\b|инди(я|и|йск)/i, "India"],
  [/\bbhutan\b|бутан/i, "Bhutan"],
  [/\bthailand\b|таиланд/i, "Thailand"],
  [/\bvietnam\b|вьетнам/i, "Vietnam"],
  [/\bindonesia\b|индонези/i, "Indonesia"],
  [/\bmalaysia\b|малайзи/i, "Malaysia"],
  [/\bsingapore\b|сингапур/i, "Singapore"],
  [/\bhong kong\b|гонконг/i, "Hong Kong"],
  [/\bphilippines\b|филиппин/i, "Philippines"],
  [/\biran\b|иран/i, "Iran"],
  [/\bqatar\b|катар/i, "Qatar"],
  [/\begypt\b|егип/i, "Egypt"],
  [/\bmorocco\b|марокко|мароккан/i, "Morocco"],
  [/\btunisia\b|тунис/i, "Tunisia"],
  [/\balgeria\b|алжир/i, "Algeria"],
  [/\bnigeria\b|нигери/i, "Nigeria"],
  [/\bghana\b|(?:^|[^а-я])ган(?:а|ы|ский)/i, "Ghana"],
  [/\bkenya\b|кени/i, "Kenya"],
  [/\btanzania\b|танзани/i, "Tanzania"],
  [/\bjamaica\b|ямайк/i, "Jamaica"]
];

export function inferFootballCountry(league: string): string | null {
  return FOOTBALL_COUNTRY_HINTS.find(([pattern]) => pattern.test(league))?.[1] || null;
}

export function isWorldCountry(country: string): boolean {
  return /^(world|мир|int|international)$/i.test(country.trim());
}
